### ISSUE TITLE
instance.php location missing

### ISSUE THREAD

**Issue by kilica** [bearsunday/BEAR.Skeleton#21]
I created bear/package and my project.

```
php composer.phar create-project bear/package
php composer.phar create-project bear/skeleton apps/Kilica.Test
```

Then, I accessed to site's top page by browser. This cause the following error.

> PHP Warning:  require(/var/www/bear/apps/Kilica.Test/var/instance.php): failed to open stream: No such file or directory in /var/www/bear/apps/Kilica.Test/var/www/index.php on line 25
> PHP Fatal error:  require(): Failed opening required 
> '/var/www/bear/apps/Kilica.Test/var/instance.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/bear/apps/Kilica.Test/var/www/index.php on line 25

/var/www/bear/apps/Kilica.Test/var/www/index.php line 25:

``` php
$app = require dirname(__DIR__) . '/instance.php';
```

I guess this should be:

``` php
$app = require dirname(dirname(__DIR__)) . '/bootstrap/instance.php';
```

**Comment by koriym** [comment]
We have two way app / framework layout.
1. BEAR.Package first. (apps are located under `apps/` )
2. App first. vendor/ (`BEAR.Package` are located under `vendor/`)

Initially, the application script determine which layout automatically. But I'm thinking to promote **app first way** and removed the logic to make it simple.

You can choose either way but you need to change your own script manually as you described here.

Thank you for the report. The documentation and `BEAR.Package` layout should be only `app first` later.
