### ISSUE TITLE
A "/" too many in uri

### ISSUE THREAD

**Issue by kilica** [bearsunday/BEAR.Skeleton#22]
After fix the Issue #21, I tried again.Then, I found another problem.

My Browser shows 404 error page.

> exception 'Ray\Di\Exception\NotReadable' with message 'Kilica\Test\Resource\Page\Index' in /var/www/bear/vendor/ray/di/src/BoundInstance.php:212
> Next exception 'BEAR\Resource\Exception\ResourceNotFound' with message 'page://self//index' in /var/www/bear/vendor/bear/resource/src/Factory.php:72

I guess this problem is caused at here !
/var/www/bear/apps/Kilica/Test/var/www/index.php line.38

``` php
    $app->page = $app->resource->$method->uri('page://self/' . $pagePath)->withQuery($query)->eager->request();
```

This should be:

``` php
    $app->page = $app->resource->$method->uri('page://self' . $pagePath)->withQuery($query)->eager->request();
```

**Comment by koriym** [comment]
Hi @kilica, Sorry too late response and than you for your concern. I really appreciated.
I think this issue is already solved.
