### ISSUE TITLE
Prod環境のカスタマイズ

### ISSUE THREAD

**Issue by ritalin** [bearsunday/BEAR.Skeleton#39]
prodコンテキストにおいて、ApcCacheが規定のキャッシュユニットとなっていますが、別のキャッシュを用いたい場合、アプリケーションごとに、ProdModuleをコピーしてきてキャッシュ構成を変更する必要があり煩雑です。

```
prodコンテキストは、コンテキストチェーンの一番外側(例：ptod-hal-api-app）のため、appコンテキストで設定を変更しても上書きされる
```

Skeltonの方で、はじめから、ProdModuleがアプリケーションのモジュールとして用意されていれば、Prod環境の構成のカスタマイズが行いやすくなると思う。

**Comment by ritalin** [comment]
ApiModule以外を置き換えている身としては、ProdModuleだけでなく、ほかのモジュール(cli, hal,..etc)もアプリケーションのモジュールとして置かれているとありがたい。

**Comment by koriym** [comment]
> ProdModuleがアプリケーションのモジュールとして用意されていれば

このやり方を繰り返すと
- 中身のない（あるいはデフォルトをインストールするだけの）テンプレートのファイルが他にも多数必要になってしまいます。
- デフォルト以外の操作をしているのかはファイルの中をチェックしないとわかりません。

ユーザーエリアのファイルをフレームワークが大量に用意するような（あるいはコマンドで用意できる）フレームワークはありますが、BEAR.Sundayの考え方はこの逆です。そもそも`Prod`というコンテキストがアプリケーションにないかもしれません。

ユーザーファイルをコピーしたりする手間のメリットと、不要なファイルを省くことを比べると後者に価値を見出しています。

**Comment by koriym** [comment]
アプリケーションテンプレートを冗長にして手間を減らすのではなく、アプリケーション共通のコンテキストをインストールできるような仕組みがあれば良いとは考えます。
