### ISSUE TITLE
PHP5.6でBEAR.Sundayをインストールする手順

### ISSUE THREAD

**Issue by kumamidori** [bearsunday/BEAR.Skeleton#54]
現状、（運用上の都合などで）PHP5.6を使いたいプロジェクトでは、BEARインストールする手順はどのようにするのが良いでしょうか？

PHP5.6 で

```
composer create-project bear/skeleton path
```
でインストールすると、BEAR.Skeleton `0.x` ブランチが使われます。
この場合、ユーザがインストール後に下記を書き換えれば問題なくアプリケーション作成に使うことができます。

- QAツールの利用方法（php-cs-fixer の引数指定 など）
- PHPUnit のバージョン 
- その他、細かい改善（1.x で提供されている内容に合わせる形）

もしPHP7系と同じこのインストール手順で良いのでしたら、1.x で提供されている機能を 0.x にバックポートするようなPRを出そうかと思っています。

**Comment by koriym** [comment]
この質問は[composer](https://github.com/composer/composer)への質問じゃないでしょうか？

**Comment by kumamidori** [comment]
すみません、PHP7以上を `require` しているのでPHP5系を使いたければ `0.x` ブランチを使ってインストールすると思っていたのですが、間違っていましたでしょうか？

今後は7.0以上をサポートにしていきたいのかもしれないと思って、PRの前に相談させて頂こうと思っていました。

**Comment by koriym** [comment]
違います！
phpのバージョンと`BEAR.Skeleton`のメジャーバージョンは対応しません。マイナーバージョンです。

**Comment by koriym** [comment]
[Release](https://github.com/bearsunday/BEAR.Skeleton/releases)でリリースノートがわかります。

![image](https://cloud.githubusercontent.com/assets/529021/26760842/4ac563e8-495d-11e7-9d1c-5ebf2b09acdf.png)

`1.4.0>=`からでphp7必須なのが分かるので、1.3.*をインストールすれば良いのが分かります。

    composer create-project bear/skeleton my-project ~1.3.0

あるいは

    composer create-project bear/skeleton my-project  1.3.*

で1.3.*系の最新版がインストールされるはずです。

**Comment by koriym** [comment]
一度インストールした後は`composer.json`の`config`でターゲットのプラットフォームを指定しておくといいでしょう。

```
{
    "config": {
        "platform":{
            "php":"5.6"
        }
    }
}
```

詳しくはcomposerのマニュアルを。

**Comment by koriym** [comment]
@kumamidori ping

**Comment by kumamidori** [comment]
ご教授ありがとうございました。理解できました。こちらはクローズ頂いてだいじょうぶです。
v1.3.x  で変更要望があり、別話題で後日ご相談しようと思います。
