### ISSUE TITLE
Run on PHP7.1 later

### ISSUE THREAD

**Issue by kumamidori** [bearsunday/BEAR.Skeleton#80]
## 質問

[PR78](https://github.com/bearsunday/BEAR.Skeleton/pull/78)  にて、 Composer で `PHP 7.0.*` の依存が定義されていました。

これを `>=7.0.0` に変更することはできるのでしょうか？
もし  `>=7.0.0`  でかまわないのであれば、Pull Request を出したいと思っています。

## 意図

`BEAR.Skeleton` で下記のような手順で Composerスクリプト（インストールフック）の動作確認を試したところ、
PHP7.1 バージョン環境下においては、 Composer のPHPバージョンの依存解決でエラーとなりました。

```
composer create-project --stability="dev" --repository-url="/path/to/my/package.json" bear/skeleton MyVendor.MyPackage 
```

package.json 
```
{
    "package": {
        "name": "bear/skeleton",
        "version": "1.7.2.beta",
        "source": {
            "url": "git@github.com:kumamidori/BEAR.Skeleton.git",
            "type": "git",
            "reference": "feature/php71_20190219"
        }
    }
}
```

version `1.7.2.beta` 、`feature/php71_20190219` が `require >= 7.0.0` であるように変更したバージョンで試したところ、エラーは出なくなり、Composerスクリプト（インストールフック）が正常終了しました。
PHP7.1 以上がデフォルトで使えるようになっている方が使いやすいと考えたことからお尋ねしました。

**Comment by koriym** [comment]
何故devのインストールなんでしょうか

**Comment by kumamidori** [comment]
通常の利用だと `dev` を使うことは無いのですが、
「自分で `bear/skeleton` を改変した開発版を用意したい（pr を出したい）」といった特殊なケースでは、検証作業時に  `dev` を使うことになると思っています。
前記の動作確認手順により、自作の開発版の動作確認（品質保証）ができます。

**Comment by koriym** [comment]
* どのようなエラーが出るんでしょうか？
 * `dev`の時だけエラーが出るんでしょうか？

**Comment by koriym** [comment]
PHP7.1での`dev`インストールを試してみましたが、問題が再現しません。
https://travis-ci.org/bearsunday/BEAR.SupportedVersions/jobs/504268751#L628

**Comment by koriym** [comment]
普通、`7.0.*`のようなバージョンをロックするような書き方はしないのですが、php-cs-fixerとかQAツールが7.3など特定のバージョンだけをサポートしない時に"仕方なく"使ってました。

**Comment by kumamidori** [comment]
## どのようなエラーが出るか

下記のようになりました（CI環境での動作記録でなくローカル環境での実行結果です。分かりにくくてすみません）。

### 手順と結果

```
$ php -v
PHP 7.1.23 (cli) (built: Nov 27 2018 16:59:25) ( NTS )

$ composer create-project --stability="dev" --repository-url="/path/to/v1.7.2/package.json" -n bear/skeleton app-dev

- Installing bear/skeleton (1.7.2): Cloning 1.x from cache
Created project in app-dev
> BEAR\Skeleton\Composer::install
composer.json for my-vendor/my-project is created.

oLoading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php 7.0.* but your PHP version (7.1.23) does not satisfy that requirement.
$
```

上記の `package.json` ファイル内容は下記です↓ ローカル環境に配置しフルパスを `--repository-url` の値に指定しました。

```
{
    "package": {
        "name": "bear/skeleton",
        "version": "1.7.2",
        "source": {
            "url": "git@github.com:bearsunday/BEAR.Skeleton.git",
            "type": "git",
            "reference": "1.x"
        }
    }
}
```

## 上記エラーの発生条件

上記手順の場合のみです。

## 同様の手順で検証を可能にする方法について

- 現状は、自作開発版の動作検証が可能なPHPバージョン環境は、 PHP v7.0.* のみと思っております。
- PHP v7.1で開発版を動作検証したいことから、v7.0 ロックをもしやめられるのであれば嬉しいなと思いました。
- v7.0 以上に変更して試すと、下記のように、プロジェクト作成に成功しました。

```
$ php -v
PHP 7.1.23 (cli) (built: Nov 27 2018 16:59:25) ( NTS )
$ composer create-project --stability="dev" --repository-url="/path/to/v1.7.2.beta/package.json" -n bear/skeleton app-dev  
Installing bear/skeleton (1.7.2.beta)                                
  - Installing bear/skeleton (1.7.2.beta): Cloning 1.x from cache                                                                                                                                                             
Created project in app-dev                                                                                                                                                                   
> BEAR\Skeleton\Composer::install                                                                                                                                                                                             
composer.json for my-vendor/my-project is created.
...（中略）...
Generated autoload files containing 636 classes
> php --run "touch('.env');"
$
```

package.json 内容

```
{
    "package": {
        "name": "bear/skeleton",
        "version": "1.7.2.beta",
        "source": {
            "url": "git@github.com:kumamidori/BEAR.Skeleton.git",
            "type": "git",
            "reference": "1.x"
        }
    }
}
```

`1.7.2.beta` で改変した内容はこちらです。

https://github.com/bearsunday/BEAR.Skeleton/compare/1.x...kumamidori:feature/php71_20190219?expand=1

**Comment by koriym** [comment]
@kumamidori 
1.7.2は`7.0.*`のみサポートしているのが`composer.json`で分かると思います。サポートしていないPHPでインストールしようとしているのでエラーが出るのは正常です。`7.1.*`だとそれ以前のバージョン`1.7.1`が正常にインストールされるはずです。

| PHP       | ver    |
|---------|------|
| PHP 7.0 | 1.7.2 |
| PHP 7.1 > | 1.7.1 |

...と書いたところで分かりました！`1.x`ブランチ（unstable)で7.0でロックされたくないという事なんですね。すいません分かりました！

しかし。`7.0.x`の時だけ問題が出るので1.7.2を作ったので`>=7.0.0`では問題があります。

**Comment by koriym** [comment]
@kumamidori `>=7.1.0`でPRを出してもらえますでしょうか？ (7.0はサポートしなくなった理由もあります）
http://bearsunday.github.io/manuals/1.0/en/version.html

**Comment by kumamidori** [comment]
@koriym 分かりづらくてすみませんでした 💦 それでは `>=7.1.0` で近日別途PRを出したいと思います。整理とサポートありがとうございました。😃

**Comment by koriym** [comment]
@kumamidori ありがとうございました！
